#!/usr/bin/env bash
# -*- mode: shell-script -*-

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Usage: $0 host|all nixos-cmd nixos-args..."
    exit 1
fi

onehost() {
	host=$1
	shift
	set -x
	out=$(nix build --json .#nixosConfigurations.${host}.config.system.build.toplevel | jq -r '.[0].outputs.out')

	nix copy -s --to "ssh://root@$host" "$out"
	nix copy -s --derivation --to "ssh://root@$host" "$out"

	if [ "$1" = "diff" ]; then
		ssh "root@$host" "nix-store -qd /run/current-system $out | xargs nix-diff --color=always" | less -R
	else
		ssh "root@$host" nix build --profile /nix/var/nix/profiles/system "$out"
		ssh "root@$host" nix shell -vv "$out" -c switch-to-configuration "$@"
	fi
	set +x
}

host=$1
shift
if [[ "$host" == "all" ]]; then
	for host in `grep '= mkHost' flake.nix | awk '{print $1}'`; do
		echo
		echo "##################################"
		echo "# $host"
		echo "##################################"
		onehost "$host" "$@"
	done
else
	onehost "$host" "$@"
fi
