groups:
  - name: node_rules
    rules:
      - alert: InstanceDown
        expr: up{job="node"} == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: Instance {{ $labels.instance }} down
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      - alert: ServiceFail
        expr: node_systemd_unit_state{state="failed"} > 0
        for: 10m
        labels:
          severity: page
        annotations:
          description: Instance {{ $labels.instance }} service {{ $labels.name }} is in failed state.
      - alert: DiskWillFillIn1Day
        expr: predict_linear(node_filesystem_free_bytes{job="node",fstype="ext4"}[6h], 24 * 3600) < 0
        for: 10m
      - alert: DiskSpace
        expr: node_filesystem_avail_bytes{fstype!~"ramfs|tmpfs|fuse.*"} / node_filesystem_size_bytes{fstype!~"ramfs|tmpfs|fuse.*"} < 0.15
        for: 10m
        annotations:
          summary: '{{ $labels.instance }} mountpoint "{{ $labels.mountpoint }}" is > 85% full'
      - alert: AptUpgradesPending
        expr: sum without(arch) (apt_upgrades_pending) > 0
        for: 10m
        annotations:
          summary: Instance {{ $labels.instance }} has apt upgrades pending
      - alert: HostRequiresReboot
        expr: node_reboot_required > 0
        for: 4h
        labels:
          severity: info
        annotations:
          summary: Host requires reboot (instance {{ $labels.instance }})
