groups:
  - name: node_rules
    rules:
      - alert: InstanceDown
        expr: up{job="node"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Instance {{ $labels.instance }} down
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      - alert: ServiceFail
        expr: node_systemd_unit_state{state="failed"} > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: Instance {{ $labels.instance }} service {{ $labels.name }} is in failed state.
      - alert: DiskWillFillIn1Day
        expr: predict_linear(node_filesystem_free_bytes{job="node",fstype=~"ext4|zfs"}[6h], 24 * 3600) < 0
        for: 10m
        labels:
          severity: warning
      - alert: DiskSpace
        expr: node_filesystem_avail_bytes{fstype=~"ext4|zfs"} / node_filesystem_size_bytes{fstype=~"ext4|zfs"} < 0.15
        for: 10m
        labels:
          severity: info
        annotations:
          summary: '{{ $labels.instance }} mountpoint "{{ $labels.mountpoint }}" is > 85% full'
      - alert: AptUpgradesPending
        expr: sum without(arch) (apt_upgrades_pending) > 0
        for: 10m
        labels:
          severity: info
        annotations:
          summary: Instance {{ $labels.instance }} has {{ $value }} apt upgrade(s) pending
      - alert: HostRequiresReboot
        expr: node_reboot_required > 0
        for: 4h
        labels:
          severity: info
        annotations:
          summary: Host requires reboot (instance {{ $labels.instance }})
      - alert: HostUptime
        expr: (time() - node_boot_time_seconds ) / (24*3600) > 30
        for: 10m
        labels:
          severity: info
        annotations:
          summary: Instance {{ $labels.instance }} has uptime > 30 days
      - alert: ZfsOfflinePool
        expr: node_zfs_zpool_state{state!="online"} > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Instance {{ $labels.instance }} has ZFS offline pool ({{ $labels.state }})
      - alert: HostNetworkBondDegraded
        expr: ((node_bonding_active - node_bonding_slaves) != 0)
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Host Network Bond Degraded (instance {{ $labels.instance }})
