groups:
  - name: pbs_rules
    rules:
      - alert: InstanceDown
        expr: pbs_up{job="pbs"} == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: PBS instance {{ $labels.instance }} down
      - alert: DailyBackupOverdue
        expr: (time() - pbs_snapshot_vm_last_timestamp{namespace="daily"}) / (3600) > 24
        for: 1h
        labels:
          serverity: warning
        annotations:
          summary: "Daily backup overdue for {{ $labels.vm_id }} on {{ $labels.instance }}: {{ printf \"%.1f\" $value }}"
      - alert: WeeklyBackupOverdue
        expr: (time() - pbs_snapshot_vm_last_timestamp{namespace="weekly"}) / (3600) > 168
        for: 1h
        labels:
          serverity: warning
        annotations:
          summary: "Weekly backup overdue for {{ $labels.vm_id }} on {{ $labels.instance }}: {{ printf \"%.1f\" $value }}"
      - alert: MonthlyBackupOverdue
        expr: (time() - pbs_snapshot_vm_last_timestamp{namespace="monthly"}) / (3600) > 840 # 35 days is max 1st Sat -> 1st Sat
        for: 1h
        labels:
          serverity: warning
        annotations:
          summary: "Monthly backup overdue for {{ $labels.vm_id }} on {{ $labels.instance }}: {{ printf \"%.1f\" $value }}"
