groups:
  - name: push_rules
    rules:
      - alert: PbsBackupFail
        expr: time() - pbs_backup_completion_timestamp_seconds > 25*3600
        for: 1h
      - alert: PostgresqlBackupFail
        expr: postgresql_backup_status == 0
        for: 1h
