groups:
  - name: smartctl_rules
    rules:
      - alert: SmartDeviceTemperatureWarning
        expr: (avg_over_time(smartctl_device_temperature{temperature_type="current"} [5m]) unless on (instance, device) smartctl_device_temperature{temperature_type="drive_trip"}) > 60
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Device temperature warning on {{ $labels.instance }} drive {{ $labels.device }} over 60°C
      - alert: SmartDeviceTemperatureCritical
        expr: (max_over_time(smartctl_device_temperature{temperature_type="current"} [5m]) unless on (instance, device) smartctl_device_temperature{temperature_type="drive_trip"}) > 70
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Device temperature critical on {{ $labels.instance }} drive {{ $labels.device }} over 70°C
      - alert: SmartStatus
        expr: smartctl_device_smart_status != 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Device has a SMART status failure on {{ $labels.instance }} drive {{ $labels.device }})
      - alert: SmartCriticalWarning
        expr: smartctl_device_critical_warning > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Disk controller has critical warning on {{ $labels.instance }} drive {{ $labels.device }})
      - alert: SmartMediaErrors
        expr: smartctl_device_media_errors > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          description: Disk controller detected media errors on {{ $labels.instance }} drive {{ $labels.device }})
      - alert: SmartWearoutIndicator
        expr: smartctl_device_available_spare < smartctl_device_available_spare_threshold
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Device is wearing out on {{ $labels.instance }} drive {{ $labels.device }})
