groups:
  - name: ups_rules
    rules:
      - alert: UpsStatus
        expr: changes(network_ups_tools_ups_status[5m]) > 0
      - alert: UpsOnBattery
        expr: network_ups_tools_ups_status{flag="OB"} == 1
        labels:
          severity: critical
