groups:
  - name: ups_rules
    rules:
      - alert: UpsStatus
        expr: changes(network_ups_tools_ups_status[5m]) > 0
      - alert: UpsOnBattery
        expr: network_ups_tools_ups_status{flag="OB"} == 1
        labels:
          severity: critical
      - alert: UpsLessThan15MinutesOfBatteryTimeRemaining
        expr: predict_linear(network_ups_tools_battery_charge[2m], 15 * 60) <= 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: UPS battery is almost empty (< 15 Minutes remaining)
