# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/safe/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/root" =
    { device = "rpool/safe/home/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/safe/home";
      fsType = "zfs";
    };

  fileSystems."/home/jeff" =
    { device = "rpool/safe/home/jeff";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E220-DC9F";
      fsType = "vfat";
    };

  fileSystems."/mnt/tank" =
    { device = "tank";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/backup" =
    { device = "tank/backup";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/backup/eris" =
    { device = "tank/backup/eris";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/backup/europa" =
    { device = "tank/backup/europa";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/backup/stuff" =
    { device = "tank/backup/stuff";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/media" =
    { device = "tank/media";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/media/movies" =
    { device = "tank/media/movies";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/media/music" =
    { device = "tank/media/music";
      fsType = "zfs";
    };

  fileSystems."/mnt/tank/media/tv" =
    { device = "tank/media/tv";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c3376a28-5e25-45f8-9935-3c017bc1cf5b"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
